# import packages

CANProvinceAbbreviation = {
    "Newfoundland and Labrador": "NL", 
    "Prince Edward Island": "PE", 
    "Nova Scotia": "NS", 
    "New Brunswick": "NB", 
    "Quebec": "QC",
    "Ontario": "ON", 
    "Manitoba": "MB", 
    "Saskatchewan": "SK", 
    "Alberta": "AB", 
    "British Columbia": "BC", 
    "Yukon": "YT",
    "Northwest Territories": "NT",
    "Nunavut": "NU"}

MimeTypeToFileExtension = {
    "application/hta": "hta",
    "application/msword": "doc",
    "application/octet-stream": "bin",
    "application/pdf": "pdf",
    "application/pgp-signature": "sig",
    "application/postscript": "ps",
    "application/rtf": "rtf",
    "application/vnd.ms-excel": "xls",
    "application/vnd.ms-powerpoint": "ppt",
    "application/vnd.ms-project": "mpp",
    "application/x-javascript": "js",
    "application/x-msaccess": "mdb",
    "application/x-tar": "tar",
    "application/zip": "zip",
    "audio/flac": "flac",
    "audio/midi": "midi",
    "audio/mpeg": "mp3",
    "audio/x-wav": "wav",
    "image/avif": "avif",
    "image/bmp": "bmp",
    "image/gif": "gif",
    "image/jpeg": "jpg",
    "image/png": "png",
    "image/svg": "svg",
    "image/svg+xml": "svg",
    "image/tiff": "tiff",
    "image/webp": "webp",
    "image/x-icon": "ico",
    "image/x-xbitmap": "xbm",
    "text/css": "css",
    "text/htm": "htm",
    "text/html": "html",
    "text/plain": "txt",
    "text/richtext": "rtx",
    "video/mp4": "mp4",
    "video/mpeg": "mpeg",
    "video/webm": "webm",
    "video/quicktime": "qt",
    "x-word/x-vrml": "vrml",
}

USAStateAbbreviation = {
    "Alaska": "AK", 
    "Alabama": "AL", 
    "Arkansas": "AR", 
    "Arizona": "AZ", 
    "California": "CA", 
    "Colorado": "CO",
    "Connecticut": "CT", 
    "District of Columbia": "DC", 
    "Delaware": "DE", 
    "Florida": "FL", 
    "Georgia": "GA", 
    "Hawaii": "HI", 
    "Iowa": "IA", 
    "Idaho": "ID", 
    "Illinois": "IL", 
    "Indiana": "IN", 
    "Kansas": "KS", 
    "Kentucky": "KY", 
    "Louisiana": "LA", 
    "Massachusetts": "MA", 
    "Maryland": "MD", 
    "Maine": "ME", 
    "Michigan": "MI", 
    "Minnesota": "MN", 
    "Missouri": "MO", 
    "Mississippi": "MS", 
    "Montana": "MT", 
    "North Carolina": "NC", 
    "North Dakota": "ND", 
    "Nebraska": "NE", 
    "New Hampshire": "NH", 
    "New Jersey": "NJ", 
    "New Mexico": "NM", 
    "Nevada": "NV", 
    "New York": "NY",
    "Ohio": "OH", 
    "Oklahoma": "OK", 
    "Oregon": "OR", 
    "Pennsylvania": "PA", 
    "Rhode Island": "RI", 
    "South Carolina": "SC", 
    "South Dakota": "SD",
    "Tennessee": "TN", 
    "Texas": "TX", 
    "Utah": "UT", 
    "Virginia": "VA", 
    "Vermont": "VT", 
    "Washington": "WA", 
    "Wisconsin": "WI", 
    "West Virginia": "WV", 
    "Wyoming": "WY"}
